
# config file specifying benchmarks to perform
configfile: "config/config.yml"

# rules for CRISPR comparisons
include: "rules/utils.smk"
include: "rules/crispr_comparison.smk"


# perform all comparisons listed in config.yml
rule all:
  input:
    expand("results/{comparison}/{comparison}_crispr_comparison.html",
      comparison = config["comparisons"]),
    expand("results/{comparison}/genome_browser_tracks",
      comparison = config["comparisons"])
