
# config file
configfile: "config/config.yml"

# rules for CRISPR comparisons
include: "rules/crispr_comparison.smk"

# perform all comparisons listed in config.yml
rule all:
  input:
    expand("results/{comparison}/crispr_comparison.html", comparison = config["comparisons"])
