
comparisons:
  example:
    pred:
      K562HiC: "resources/example/input/K562.ABC.Predictions.K562HiC.chrX.ENCODE.format.txt.gz"
      AvgHiC: "resources/example/input/K562.ABC.Predictions.AvgHiC.chrX.ENCODE.format.txt.gz"
    expt:
      "resources/example/input/K562.ExperimentalData.slim.txt"
    pred_config: "resources/example/input/pred_config_edit.txt"
    pred_threshold:
      K562HiC: 0.015
      AvgHiC: 0.015
    expt_positive_column: "Regulated"
    cell_name_mapping: NULL
    ignore_expt_missing_predictions: FALSE
    min_sensitivity: 0.7
