
# comparisons to be performed by the pipeline, copy-paste example for a template
comparisons:
  example:
    pred:
      K562HiC: "resources/example/input/K562.ABC.Predictions.K562HiC.chrX.ENCODE.format.txt.gz"
      AvgHiC: "resources/example/input/K562.ABC.Predictions.AvgHiC.chrX.ENCODE.format.txt.gz"
    expt:
      "resources/example/input/K562.ExperimentalData.slim.txt"
    gene_universe: "resources/example/input/genes.txt"
    pred_config: "resources/example/input/pred_config.txt"
    expt_positive_column: "Regulated"
    cell_name_mapping: NULL
