
# comparisons to be performed by the pipeline, copy-paste example for a template
comparisons:
  example:
    pred:
      K562HiC: "resources/example/K562_ABC_K562HiC_chrx.txt.gz"
      AvgHiC: "resources/example/K562_ABC_AvgHiC_chrx.txt.gz"
    expt:
      "resources/example/experimental_data_chrX.txt.gz"
    gene_universe: "resources/example/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.sorted.chrX.bed.gz"
    pred_config: "resources/example/pred_config.txt"
    cell_type_mapping: 
      K562HiC: "resources/example/ABC_cell_type_mapping.txt"
      AvgHiC: "resources/example/ABC_cell_type_mapping.txt"
