
# comparisons to be performed by the pipeline, copy-paste example for a template
comparisons:
  example:
    pred:
      ABC: "resources/example/ABC_K562_Fulco2019Genes_GRCh38.tsv.gz"
    expt: "resources/example/EPCrisprBenchmark_Fulco2019_K562_GRCh38.tsv.gz"
    gene_universe: "resources/genome_annotations/CollapsedGeneBounds.hg38.bed"
    tss_universe: "resources/genome_annotations/CollapsedGeneBounds.hg38.TSS500bp.bed"
    pred_config: "resources/example/pred_config.txt"
    include_col: Null
    cell_type_mapping: 
      ABC: "resources/example/ABC_cell_type_mapping.txt"
    dist_bins_kb: [0, 20, 100, 2500]
    expressed_genes: "resources/genomic_features/K562_expressed_genes.tsv"
    gene_features: Null
    enh_features: Null
    enh_assays: Null
    auc_left_rectangle: FALSE
