
# comparisons to be performed by the pipeline, copy-paste example for a template
comparisons:
  example:
    pred:
      dev: "/oak/stanford/groups/engreitz/Users/atan5133/abc_run_comparisons/results_dev_08_24_double_x/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
      atac: "/oak/stanford/groups/engreitz/Users/atan5133/abc_run_comparisons/results_dev_08_24_double_x/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
    expt: "/oak/stanford/groups/engreitz/Projects/Benchmarking/CRISPR_data/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"
    gene_universe: "resources/genome_annotations/CollapsedGeneBounds.hg38.bed"
    tss_universe:  "resources/genome_annotations/CollapsedGeneBounds.hg38.TSS500bp.bed"
    pred_config: "resources/example/pred_config.txt"
    cell_type_mapping: 
    dist_bins_kb: [0, 20, 100, 2500]
    gene_features: Null
    enh_features: Null
    enh_assays: Null
