
# comparisons to be performed by the pipeline, copy-paste example for a template
comparisons:
  Ramil:
    pred:
      ABC: "/path/to/abc-predictions"
      Ramil: "/path/to/ramil-predictions"
    expt: "/path/to/crispr/data"
    gene_universe: "resources/annotations_GRCh38/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.bed"
    tss_universe: "resources/annotations_GRCh38/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed"      
    pred_config: "resources/distal_regulation_comparison/pred_config.txt"
    cell_type_mapping:
      ABC: "resources/distal_regulation_comparison/ABC_cell_type_mappings.txt"
    dist_bins_kb: [0, 20, 50, 100, 2500]
    gene_features: Null
    enh_features: Null
    enh_assays: Null

